### PR TITLE
Implement issue #4: Move JMX support to a separate module

### PR DESCRIPTION
**Pull request by drem-darios**
Here is what I came up with for the JMX module. Let me know if anything looks out of place. All unit tests pass just fine :-)

### CODE REVIEW

**Comment by benas** [comment]
Fantastic!! Thank you for this addition :+1: 

I'll merge your PR and add you to the contributors list asap :-)

**Comment by drem-darios** [comment]
Great! Glad to help out :-)

**Comment by drem-darios** [comment]
Hey @benas Looks like the changes you made conflict with this branch :-/ Are you going to resolve merge conflicts or do you want me to do it?

**Comment by drem-darios** [comment]
Never mind. I got bored and resolved the merge conflicts. Build passes. It can be merged whenever :+1:

**Comment by benas** [comment]
Great! thank you for resolving this conflict.

I've merged your PR into the master branch.

I planned to rewrite all tests with Mockito (it's better than the current stubs used in tests) and then I will prepare a new release. It should come very soon, keep tuned :-)

Thank you for your contribution!:+1:

**Comment by drem-darios** [comment]
Glad to help :-)

**Pull request merged**
